name: Deploy
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      # Optional, bis im Repo gepinnt: erzwingt 6.x ohne Lockfile dauerhaft zu verändern
      - name: Ensure next-seo 6.x
        run: |
          yarn add -E next-seo@6.8.0 --non-interactive
          node -e "const v=require('next-seo/package.json').version; if(!/^6\./.test(v)){console.error('next-seo != 6.x:', v); process.exit(1)}"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build (static export)
      run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
