name: Deploy

on:
  push:
    branches: [main]

jobs:
  github_pages_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies and export site
        run: |
          yarn install
          yarn export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.QUADREL_TOKEN }}
          publish_dir: ./out
          user_name: github-actions-bot
          user_email: support+actions@github.com
